### PR TITLE
#829 - Removing refreshToken schema requirement for Oauth

### LINKED ISSUE #829: Google Oauth returns an error after access token expires
The application seems to be throwing an error once the access token expires, as there's no refresh token except after the first authorization.

To get around this for login purposes, you can revoke the access in the Google Account security management.

As far as reproducing this:
 - Log in via Google Oauth
 - Hit log out
 - Immediately try to log back in with same account
 - You should hit an error, which may be different depending on version.

1.11.2 looks like:
```
{
statusCode: 401,
error: "Unauthorized",
message: "The record has validation errors"
}
```

I'm following up this issue with a PR

### PR DESCRIPTION
**Pull request by markdboyd**
**Summary:** Summary of changes

Fixes #829 

## Changes

* Remove `refreshToken` as a required field for the access tokens schema
* Adds test for token response without `refreshToken`

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

### CODE REVIEW

File: packages/api/tests/endpoints/token.js [hunk 1]
```diff
@@ -204,6 +204,33 @@ test.serial('When using Earthdata Login, GET /token with a code stores the acces
   stub.restore();
 });
 
+test.serial('When OAuth provider returns no refresh token, GET /token with code and state results in redirect with access token', async (t) => {
```
Comment (markdboyd) [inline packages/api/tests/endpoints/token.js]: @yjpa7145 Now that I've added a test to prove that create an access token record succeeds with only an access token value, is this test necessary? The test is generally the same as other tests proving that the correct token is returned from a mocked access token response. The only difference here is explicitly not providing a `refreshToken` in the mocked access token response. But the only reason that missing property would matter is schema validation when creating the access token record and I added the other test to prove that it will not matter.

**Comment by markdboyd** [comment]
@yjpa7145 I opted to not add any explicit checking for the existence of the refresh token in the initial access token response from Earthdata login. My thinking is that we shouldn't throw errors if Earthdata doesn't include a refresh token in its initial token response, otherwise login from the dashboard would fail and that would be confusing behavior given that the only real problem is that subsequent token refreshing will fail.

For the refresh token process itself, logically it already checks whether you passed it a refreshToken:

https://github.com/nasa/cumulus/blob/be59452b0134a8298d51796bada2d013fa92dfda/packages/api/lib/EarthdataLogin.js#L178

So I'm not sure if there's anything else to do there.

What do you think?

File: packages/api/tests/endpoints/token.js (hunk 1 above)
Comment (yjpa7145) [reply packages/api/tests/endpoints/token.js]: I'm fine with removing this test.
